set nocompatible
filetype indent plugin on
syntax on
set nowrap
set number
set relativenumber
set ignorecase
set smartcase
set hlsearch
set incsearch
set wildmenu
set ruler
set showmatch
set hidden
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set laststatus=2
set splitright
set splitbelow

set nobackup
set nowb
set noswapfile

set autoread
au FocusGained,BufEnter * silent! checktime

set vb t_vb=
set viminfo=
set lazyredraw

colorscheme desert
set background=dark
highlight Normal ctermbg=NONE guibg=NONE
highlight NonText ctermbg=NONE guibg=NONE

au FileType markdown set wrap
