set nocompatible
filetype indent plugin on
syntax on
set number
set relativenumber
set ignorecase
set smartcase
set hlsearch
set incsearch
set wildmenu
set ruler
set showmatch
set hidden
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set laststatus=2
set splitright
set splitbelow
try
    colorscheme habamax
catch
endtry
