#!/usr/bin/env bash
# Quickly rip the vst3 folder out of an installer

set -e

VSTPATH="/Library/Audio/Plug-Ins/VST"
VST3PATH="/Library/Audio/Plug-Ins/VST3"

if [[ -z $1 ]]; then
    echo "usage: $0 PKG"
    exit 1
elif [[ ! -e $1 ]]; then
    echo "error: $1 is not a valid path"
    exit 1
fi

path=$(realpath $1)
echo "Processing $path"

# TODO: add support for zip archives
tmpdir="/tmp/$(basename $path)"
rm -rf $tmpdir
pkgutil --expand-full $path $tmpdir

artifactpath=$(find $tmpdir -type d -name "*.vst3" -print -quit || find $tmpdir -type f -name "*.vst3" -print -quit)
if [[ -z $artifactpath ]]; then
    echo "error: Could not find VST3 assets inside pkg"
    exit 1
fi
echo "Found $artifactpath"

echo "Attempting to move plugin to $VST3PATH"
sudo mkdir -p $VST3PATH

sudo cp -r $artifactpath $VST3PATH
echo "Plugin successfully copied to $VST3PATH/$(basename $artifactpath)"
