theme = "rose_pine_moon_nobg"

[editor]
line-number = "relative"
scrolloff = 10
auto-pairs = false
auto-format = false
default-yank-register = "+"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
wrap-indicator = ""

[keys.normal]
"=" = ":format"
D = "@vgld"
