theme = "ayu_dark"

[editor]
line-number = "relative"
auto-pairs = false
auto-format = false
default-yank-register = "+"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
auto-signature-help = false

[keys.normal]
"=" = ":format"
D = "@vgld"
