[[language]]
name = "html"
formatter = { command = 'prettierd', args = [".html"] }

[[language]]
name = "css"
formatter = { command = 'prettierd', args = [".css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettierd', args = [".js"] }

[[language]]
name = "lua"
formatter = { command = "stylua", args = [ "-" ] }

[[language]]
name = "bash"
formatter = { command = 'shfmt', args = ["-i", "4"] }
