[[language]]
name = "bash"
formatter = { command = 'shfmt', args = ["-i", "4"] }

[[language]]
name = "c"
file-types = ["c", "h"]
indent = { tab-width = 4, unit = "    " }
language-servers = [ { name = "clangd", except-features = ["format"] } ]

[[language]]
name = "markdown"
soft-wrap.enable = true
formatter = { command = 'prettierd', args = [".md"] }

[[language]]
name = "lua"
formatter = { command = "stylua", args = [ "-" ] }

[[language]]
name = "html"
formatter = { command = 'prettierd', args = [".html"] }

[[language]]
name = "css"
formatter = { command = 'prettierd', args = [".css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettierd', args = [".js"] }

[[language]]
name = "nix"
formatter = { command = "nixfmt" }
